### ISSUE TITLE
Incorrect Keil project files for the GD32305R-START

### ISSUE THREAD

**Issue by Rocky04** [CommunityGD32Cores/gigadevice-firmware-and-docs#1]
Not sure if the purpose of this GitHub is just to provide a backup but I want at least point out that there are some issues with the project files provided from GigaDevice.

For example my GD32305R-START has a GD32F305RB and not a [GD32F305RC ](https://github.com/CommunityGD32Cores/gigadevice-firmware-and-docs/blob/028226089f658b8439052c1faee554efe636188c/GD32F30x/GD32F30x_Demo_Suites_V2.2.0/GD32305R_START_Demo_Suites/Projects/01_GPIO_Running_LED/MDK-ARM/GD32305R_START.uvproj#L15)chip and so the flash and RAM size isn't correct. In addition this chip don't has a FPU so the value for [RvdsVP should be 1 not 2](https://github.com/CommunityGD32Cores/gigadevice-firmware-and-docs/blob/028226089f658b8439052c1faee554efe636188c/GD32F30x/GD32F30x_Demo_Suites_V2.2.0/GD32305R_START_Demo_Suites/Projects/01_GPIO_Running_LED/MDK-ARM/GD32305R_START.uvproj#L220), which triggers a hard fault when the main routine should be called on init without MicroLib.

**Comment by obra** [comment]
indeed, this is just a public archive of the zip files provided by gigadevice since they don’t always keep old versions around. it does appear that gigadevice sometimes custom builds their devboards with alternate chips in the same series, at least sometimes based on customer request. I’m going to resolve this ticket because this isn’t a repository where we make changes to their code
